service: nest-serverless-lambda-demo

plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs14.x

functions:
 get-docs:
   handler: src/documentation/main.handler
   events:
    - http:
       method: any
       path: /{any+}
 get-cats: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/cats/main'
   handler: src/cats/main.handler
   events:
     - http:
         method: any
         path: /cats/{any+}

 get-dogs: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/dogs/main'
   handler: src/dogs/main.handler
   events:
     - http:
         method: any
         path: /dogs/{any+}

custom:
  optimize:
    external: ['swagger-ui-dist']
    exclude: ['**.css']
    minify: false
