version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  run-test-e2e:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Test e2e
          command: npm run test:e2e
  deploy-lambda:
    parameters:
      stage-name:
        type: string
    docker:
      - image: cimg/node:16.10
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless
            serverless plugin install -n serverless-plugin-typescript
            serverless plugin install -n serverless-offline
            serverless plugin install -n serverless-plugin-optimize
      - run:
          name: Deploy with Serverless CLI
          command: |
            sls deploy --stage << parameters.stage-name >>
  approve-pre:
  approve-pro:

workflows:
  main:
    jobs:
      - run-test-e2e
      - deploy-lambda:
          stage-name: dev
          requires:
            - run-test-e2e
      - approve-pre:
          type: approval
      - deploy-lambda:
          stage-name: pre
          requires:
            - approve-pre
